name: {{name.snakeCase()}}_repository
description: {{name.pascalCase()}}Repository pure dart package.
version: 0.0.1

environment: 
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_serializable: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0